version = 1
SPDX-PackageName = "wst"
SPDX-PackageSupplier = "Ingo Ruhnke <grumbel@gmail.com>"

[[annotations]]
path = [
  "README.md",
  "VERSION",
  "**/VERSION",
  ".gitignore",
  "**/.gitignore",
  "display/.clang-tidy",
  "flake.lock",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Ingo Ruhnke <grumbel@gmail.com>"
SPDX-License-Identifier = "GPL-3.0-or-later"

# Generated for the demos
[[annotations]]
path = "demos/data/sprites/blob.png"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Ingo Ruhnke <grumbel@gmail.com>"
SPDX-License-Identifier = "GPL-3.0-or-later"

# largetux-jump-right-0.png from SuperTux 0.1.x (Milestone 1),
# relicensed by its author from GPL-2.0-or-later
[[annotations]]
path = "demos/data/tux.png"
precedence = "aggregate"
SPDX-FileCopyrightText = "2004 Ingo Ruhnke <grumbel@gmail.com>"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = ["demos/data/Vera.ttf", "gui/extra/Vera.ttf"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2003 Bitstream, Inc."
SPDX-License-Identifier = "Bitstream-Vera"

# Generated by glad 2.0.8, https://glad.dav1d.de/
[[annotations]]
path = ["display/external/glad/include/glad/gl.h", "display/external/glad/src/gl.c"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2013-2022 David Herberth, The Khronos Group Inc."
SPDX-License-Identifier = "(WTFPL OR CC0-1.0) AND Apache-2.0"

[[annotations]]
path = "display/external/glad/include/KHR/khrplatform.h"
precedence = "aggregate"
SPDX-FileCopyrightText = "2008-2018 The Khronos Group Inc."
SPDX-License-Identifier = "MIT-Khronos-old"
